### ISSUE TITLE
Instance Segmentation

### ISSUE THREAD

**Issue by talent-less** [NVlabs/SegFormer#3]
Can SegFormer be applied to other tasks like instance segmentation?

**Comment by xieenze** [comment]
SegFormer cannot do instance segmentation directly, but you can build an instance segmentation pipeline based on SegFormer.

**Comment by kaixin-bai** [comment]
I tried to use mixvisiontransformer in segformer to replace the image encoder in instance segmentation, and change the neck part to fit ViT model, but the pretrain really costs resources, the batch size can only be 1 or 2 on A6000 single card. I think if someone has really lots of cards could try the pretrain task with segformer, otherwise just give it up.
